// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations run DDL; the unpooled connection avoids pgbouncer lock/prepared-statement quirks.
    // The app's runtime client (lib/db/) uses the pooled DATABASE_URL via the Neon adapter instead.
    url: process.env["DATABASE_URL_UNPOOLED"],
  },
});
